#version: '3'
#
#services:
#  mysql:
#    image: mysql:8.0.34
#    container_name: mysql-springbootdb
#    ports:
#      - "3307:3306"
#    environment:
#      - MYSQL_DATABASE=springbootdb
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_ROOT_PASSWORD=root
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#volumes:
#  mysql-data: